Follow standard convention in exit status of /etc/init.d/castle status.
--HG--
branch : v2
extra : transplant_source : %C3%E1%F2%91%D0%06%8B%13%0A%D5%28w%40%C7%AC%8F%81%17%90%E5

diff --git a/castle-tools/utils/castle b/castle-tools/utils/castle
--- a/castle-tools/utils/castle
+++ b/castle-tools/utils/castle
@@ -64,6 +64,12 @@ force_reload() {
 rh_status() {
     # run checks to determine if the service is running or use generic status
     kernel_fs_running
+    # Exit status as per: http://refspecs.linuxbase.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+    if [ ! $? -eq 0 ]; then
+	exit 3
+    else
+	exit 0
+    fi
 }
 
 rh_status_q() {
